spring:
  application:
    name: produto-ms
  devtools:
    remote:
      secret: 'D&vo&&iFBkKPD5IqwU7,ix{#iC7qC1RrE3y$6dip;GI}sBr9[Aw"52E9M@v!<(4'
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://produto-db:3306/produto-db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: ifljava

logging:
  level:
    org:
      springframework:
        web: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://servidor:8081/eureka

server:
  port: 0